### ISSUE TITLE
[tracking] Pre-launch checklist

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#107]
**This issue is to keep track of miscellaneous items for devhub to remember to update before launching:**

- [x] 🛠 Fix/address all TODOs in docs: https://github.com/substrate-developer-hub/substrate-docs/issues/158
- [x] 🖼 Remove FRAME V2 stuff (FRAME, Pallets, Macros, Metadata, Storage in docs)
- ~~📚📓 Archiving + update migration messaging in READMEs.~~ move to #389
  - [x] Delete [Substrate Github Wiki](https://github.com/paritytech/substrate/wiki) - see: https://github.com/substrate-developer-hub/substrate-docs/issues/105
  - [x] [Substrate.dev](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/) (https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1154)
  - [x] [Substrate Recipes](https://github.com/substrate-developer-hub/recipes/)
  - [x] Enterprise Sample, see: https://github.com/substrate-developer-hub/substrate-enterprise-sample/pull/89
- [x] 🔗 Tutorials have correctly linked solutions
- [x] #197
- [x] 👀 PR in Substrate repository to fix all substrate.dev/ links (redirects won't work for most because of URL slug change) for e.g. [FRAME and Runtime here](https://substrate.dev/rustdocs/latest/pallet_lottery/index.html)
- [x] ⛴ Porting over all existing issues and PRs from other repos **and add `docs-migration` tag**
  - [x] https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/
  - [x] https://github.com/substrate-developer-hub/substrate-how-to-guides/ 
- ~~Complete content review~~ -- move to #192 

### Additional items:
- #390
- [x] HTGs cleanup: "how to register a parachain" and "para id" guides should probably be removed. That content is covered in the Cumulus tutorial. Same with "start-collator-node" @NukeManDan and @midegdugarova WDYT - can you take action on this please? ( @NukeManDan : I can get this started in #239 )

**Comment by NukeManDan** [comment]
Pre-launch:

- [ ] https://github.com/substrate-developer-hub/substrate-docs/issues/158
- [x] Remove FRAME V2 stuff (FRAME, Pallets, Macros, Metadata, Storage in docs)
- [ ] Archive strategy: 
  - [ ] https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/
  - [ ] https://github.com/substrate-developer-hub/recipes/
  - [ ] Substrate Github Wiki (https://github.com/substrate-developer-hub/substrate-docs/issues/105)
  - [ ] https://github.com/substrate-developer-hub/substrate-enterprise-sample/pull/89 
  - [ ] Others? More stale repos in this github org?
- [ ] Tutorials have correctly linked solutions (#192 should address)
- [ ] PR in _all repositories_ to fix all substrate.dev/ links (redirects won't work for most because of URL slug change)
  - [ ] https://github.com/paritytech/ 
  - [ ] https://github.com/w3f/
  - [ ] https://github.com/polkadot-js/
- [ ] Porting over all existing issues and PRs from other repos **add `docs-migration` tag**
  - [x] https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/
  - [ ] Others?
- [ ] Archive 

### Additional items in #57 #192

**Comment by NukeManDan** [comment]
Not sure of the context @lsgunnlsgunn - this is a tracking issue not related to Nicks specifically. Let's continue in #390
