### ISSUE TITLE
[Tracking] Migrate checklist for `main-md` -> `main` and launch to docs.substrate.io

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#1074]
Please edit this comment (or add more below) for the things needed before we launch the `main-md` work

(see also https://www.notion.so/paritytechnologies/Final-checklist-main-md-merge-c675665b9d9d4019a9bbc2a5ecf2872e internal to parity)

- [x] Build the information architecture Docs sections (Fundamentals, Install, Build, Test), Tutorials, Reference.
- [x] Move old content that we'll iterate on into the new info architecture.
- [x] Update paths to images
- [x] Update all internal links, e.g.: `/tutorials/get-started/build-local-blockchain/` --> `/tutorials/work-with-pallets/add-a-pallet/` 
- [x] Update Rustdocs links in `main-md` to match #1072 @NukeManDan 
- [x] Spot check pages for missing or broken images, merge conflicts, major uglies
- [x] Add a Major Update Released banner or alert to the site.
- [x] Spot check links if doing manual checking (add a link checker CI as stretch goal)
- [x] Add the location of archived content to the 404.
  - [x] README linked
  - [x] 404 page linked
- [x]  Check with stakeholders if any redirects are required (best practice would be to allow users to go to 404 page for all unpublished pages).
- [x] Confirm ok with stakeholders to build the site from branch `main-md`.
  - Jonny to help make sure this is good to go on netlify.
  - [x] default branch set correctly
- [ ] Archive `main` and (possibly) host it somewhere (the old repo will still be visible/discoverable). 
- [x]  Cross browser testing (Chrome 69%, FF 11%, Safari 7%, IE 5%, iOS Safari 3%)

### Triage plan after launch

- [ ] Ensure SEO is cleared/updated so google & friends don't point people to now dead links
  - [ ] rustdocs example https://www.google.com/search?q=bounded+vec+substrate&oq=bounded+vec+substrate&ie=UTF-8 at time of writing -> https://docs.substrate.io/rustdocs/latest/frame_support/storage/bounded_vec/struct.BoundedVec.html
- [ ] https://github.com/substrate-developer-hub/substrate-docs/pull/1108
- [ ] assets dir setup and for now all downloaded files are referenced in a full URL to guthub, hookedup latter on 
- [ ] scan stack exchange for links and replace with mods powers (Dan, Bruno)
- [x] Get a blog and press release arranged once we are sure that all fires post launch are done. 
  - [x] twitter post to start
  - [x] substrate news letter
- [ ] Ensure dependabot is happy
- [ ] Contributing guide finished for `main-md`
- [ ] Clean issues and PRs from main md and migrate relevant open ones to the new branch. 

### `Nice-to-have`s

- As much as possible, no deeply nested folder structure for content (at least) - make it as top-level as we can (no internationalization is used at hte moment for instance). a symb-link might be OK, but only is required.

**Comment by NukeManDan** [comment]
## Content review:

Here is a stab at an e2e review :grin: 

## **Blocking release**

- [ ] on opening the root page`/` has wrong links to `/v3/...` content, needs to be correctly linked into content. Explore Documentation section at a minimum.
- [ ]  Home page nav goes to Quickstart, not the [home/index page](https://github.com/substrate-developer-hub/substrate-docs/blob/main-md/content/md/en/docs/main-docs/index.md) - unclear where this page exists in rendered site. Sould be the first docs page users see when arriving from navbar
- [ ] quick start page is missing mention of nightly - this must be there. I is burried deep in the install section (this _will_ have many users stuck)
- [ ] "This sample [index.html](https://substrate-docs-md.netlify.app/examples/quickstart/index.html/) provides a simple example of how to use JavaScript and HTMLto get an account balance." - index page is a 404. Why do we use this instead of the front end template? Where does the example file exist in this repo? why not name if something not generic?
- [ ] The Substrate empowers builders page (top level index I guess) has no link to the quickstart - it should!
- [ ] "Blockchains typically use tokens to represent the value of assets in an account and network participants purchase tokens outside of the chain through an exchange. " - no mention of exchange in this repo.
