### ISSUE TITLE
Test all tutorials work with `monthly-2021-11` release of Substrate

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#132]
- [x] #606

### Please `convert to issue` and assign yourself :pray:

Pro tip for anyone helping here: use the `convert to issue` option that any unchecked checkmark in the issue here has to make a new issue and assign yourself to it:

![image](https://user-images.githubusercontent.com/35669742/135142007-7633025c-7afb-42b0-b1e3-0b495375e5ef.png)

## Tests completed for `monthly-2021-10` :

- [x] 01-create-your-first-substrate-chain -- test with `monthly-2021-11`
- [x] #597
- [x] 03-permissioned-network -- test with `monthly-2021-11`
- [x] 04-forkless-upgrades -- test with `monthly-2021-11`
- [x] 05-private-network -- test with `monthly-2021-11`
- [x] 06-node-metrics -- test with `monthly-2021-11`
- [x] 07-add-a-pallet -- test with `monthly-2021-11`
  - UPDATE based on new metadata v14. Mapping types in Apps UI and in FE template _should not_ be required.  
- [x] #511
  - metadata update details matter here too

## Test completed for non-monthly tag & 
- [ ] Test -- 08-ink-workshop 
  - [ ] Need clarification on: https://github.com/paritytech/substrate-contracts-node/issues/9
- [ ] #133
- [x] #134
  - [ ] Need clarification on: https://github.com/paritytech/frontier/issues/483

**Comment by NukeManDan** [comment]
Pro tip for anyone helping here: use the `convert to issue` option that any unchecked checkmark in the issue here has to make a new issue and assign yourself to it:

![image](https://user-images.githubusercontent.com/35669742/135142007-7633025c-7afb-42b0-b1e3-0b495375e5ef.png)

cc @al3mart @sacha-l @jimmychu0807 and anyone else that wants to help out here :pray:

**Comment by JoshOrndorff** [comment]
I can take ownership of the Frontier template and the Frontier workshop.

**Comment by NukeManDan** [comment]
Closing and moving to another tracker.
