### ISSUE TITLE
Update & Test 09-cumulus-workshop

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#133]
uses non-monthly tag & https://github.com/substrate-developer-hub/substrate-parachain-template/
- [x] remove formatting files (prettier, editorconfig)
- [x] https://github.com/substrate-developer-hub/substrate-parachain-template/pull/73
- [x] error check in content
- [ ] port updates from original (https://github.com/substrate-developer-hub/cumulus-workshop/pull/104)
- [x] Needs cleaning up & fix of links / URLs throughout
- [x] PoV is mentioned for the first time without any context (see [here](https://docs.substrate.io/tutorials/v3/cumulus-workshop/pt2#3-cross-chain-message-passing-xcmp))
- [x] Its confusing what's happening in `/v3/cumulus-workshop/pt3#kickstart`
- [x] [This step](https://docs.substrate.io/tutorials/v3/cumulus-workshop/pt3#2-using-the-template) and the one after seem incomplete or just don't have much of a purpose
- [ ] [Here](https://docs.substrate.io/tutorials/v3/cumulus-workshop/pt3#1-parathread-registration) you loose readers - mean to learn how to register a parathread here? Ah you have multiple steps that follow, I see. I think you should better introduce this section, turning steps 1 and 2 into more of the "overview" of the next steps
- [x] A congrats and next steps section like the other tutorials.
- [x] ~Port Chinese translation & acknowledgement~ new translation needed based on content changes 
- [ ] test polkadot-launch (https://github.com/paritytech/polkadot-launch/pull/143  && https://github.com/substrate-developer-hub/cumulus-workshop/pull/101#issuecomment-935376451 ) 
- [ ] port over all issues or fix
  - [x] https://github.com/substrate-developer-hub/cumulus-workshop/issues/93

**Comment by NukeManDan** [comment]
uses non-monthly tag & https://github.com/substrate-developer-hub/substrate-parachain-template/
- [ ] https://github.com/substrate-developer-hub/substrate-parachain-template/pull/73
- [ ] error check in content

**Comment by NukeManDan** [comment]
@jimmychu0807 can you confirm that polkadot launch is working in #203 ? I pulled in your last update.

**Comment by jimmychu0807** [comment]
@NukeManDan for `polkadot-launch`, the issue you mentioned shouldn't block the `test polkadot-launch` from getting check mark. `polkadot-launch` works for the example given in the tutorial, a 3-node relay chain, and 2 parachain each with one node. I have updated the config in the static asset to reflect that. 

But that is an enhancement that could be made on `polkadot-launch` side, or document that.
