### ISSUE TITLE
PBA Transcripts from Week 1

### ISSUE THREAD

**Issue by lisa-parity** [substrate-developer-hub/substrate-docs#1639]
Basic plan:

- [x] Convert lecture videos to text files 
- [x] Upload transcripts to a Google drive
- [x] Rough edit
- [ ]  Polish edited text
- [ ] Integrate (or replace) existing topics with the new material

**Comment by har00ga** [comment]
Completed
