### ISSUE TITLE
PBA Transcripts from Week 2

### ISSUE THREAD

**Issue by lisa-parity** [substrate-developer-hub/substrate-docs#1640]
Basic plan:
- [ ] Convert lecture videos to text files 
- [ ] Upload transcripts to a Google drive
- [ ] Rough edit
- [ ] Polish edited text
- [ ] Integrate (or replace) existing topics with the new material

**Comment by har00ga** [comment]
Completed
