### ISSUE TITLE
[Tracking] Archive unmaintained and unused Devhub repositories

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#389]
We may also consider _deleting_ repositories that are no longer relevant or useful:

- [x] https://github.com/substrate-developer-hub/substrate-proof-of-existence 
  - Covered in tutorials already?
- [ ] https://github.com/substrate-developer-hub/utxo-workshop
  - Highly requested to this day... maybe we can point those to https://github.com/kulupu/kulupu ?
- [ ] https://github.com/substrate-developer-hub/rustdocs 
  - @jimmychu0807 related to #352 we might want to simply copy these builds into the new repo? 
- [ ] https://github.com/substrate-developer-hub/substrate-tools 
  - @chevdor @stiiifff maybe marketplace replaces this...? and the Awesome list?
- [ ] https://github.com/substrate-developer-hub/migration-example
  - Related to #163 cc @apopiak 
- [x] https://github.com/substrate-developer-hub/frontier-workshop/
  - @JoshOrndorff you gave a great sub0 workshop that should replace this soon?
  - https://github.com/substrate-developer-hub/substrate-docs/issues/177

- - - 

Related to the already archived https://github.com/substrate-developer-hub/substrate-enterprise-sample cc @riusricardo 
- [ ] https://github.com/substrate-developer-hub/substrate-cms
- [ ] https://github.com/substrate-developer-hub/pallet-did

**Comment by sacha-l** [comment]
@NukeManDan : IIRC this list has been taken care of. Can you confirm and close here if this is the case? Thanks 😎

**Comment by NukeManDan** [comment]
No, all of these unchecked are still in need of feedback and all still are public regular repos (not archived) 🙏
