### ISSUE TITLE
[tracking] General minor content updates

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-docs#57]
This issue is to keep track of miscellaneous items for devhub to remember to update:

- [ ] Some links to our Rustdocs use "https://docs.rs/*". 
- [ ] [This section](/v3/tutorials/add-a-pallet/publish) in the Add A Pallet tutorial is already a how-to guide. I think we should just point to it in the "Next steps -> Learn more" section of that tutorial. For now it's just an optional part of the tutorial. Also a bit awkward and more fitting as a HTG anyway. 
- [ ] Do a pass searching for "todo" keyword in devhub content and remove / address them
- [ ]  Add all Tooling and Parachain how-to guides
- [ ] HTGs cleanup: "how to register a parachain" and "para id" guides should probably be removed. That content is covered in the Cumulus tutorial. Same with "start-collator-node"

External:
- [ ] Fix links to docs in crates ⚠️ (for example [FRAME and Runtime](https://substrate.dev/rustdocs/latest/pallet_lottery/index.html))

**Comment by sacha-l** [comment]
Items moved to  #107.
