### ISSUE TITLE
[Tracking] Rustdocs improvements

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#678]
The present state of rustdocs exposed by the devhub has many loose ends to close up that will help a lot 
- [ ] #637 (easy)
- [ ] #428 (medium, depends on upstream issues, so maybe hard)
- [ ] #389 (medium, devhub rust docs and/or substrate gh-pages rustdocs)
- [ ] #352 (hard & kinda blocked on #478 & #477 ) we should move `latest` for docs as well and maintain a tag & build for this somewhere.
  - [ ] #182
- [ ] https://github.com/paritytech/substrate/issues/10089 (easy) need to come to agreement on direction and mention this explicitly in devhub for those looking(?), related to rustdocs
