### ISSUE TITLE
[Tracking] Rococo updates

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#936]
## [Existing page](https://docs.substrate.io/tutorials/v3/cumulus/) and its [source](https://github.com/substrate-developer-hub/substrate-docs/blob/main/v3/tutorials/09-cumulus/d-rococo/index.mdx)

- [ ] [Internal figma updates requested](https://www.notion.so/paritytechnologies/Rococo-Network-31b842935a8a49b3b2ea10b2be682e52?d=1fa77ec08b9b4e18b72094d95188ed38) - new images and flow of page.
  - [ ] Meeting needed with team to sync on getting updates ASAP into docs here, not left in figma
- [ ] #609 - further updates to finalized flow
- [ ] TBD - Delivery services support issues on Rococo runtime // community communication & management // pseudo `sudo` based governance owners... etc. 
- [ ] Update the Polkadot Wiki in a way that **doesn't need ongoing maintenance**: https://wiki.polkadot.network/docs/build-pdk#testing-a-parachain

cc @BenWhiteJam @SBalaguer @Goranch3 @je-boska @john-parity
